language: php
sudo: false

php:
  - 5.6
  - 7.0
  - nightly
  - hhvm

os:
  - linux

env:
  - PREFER_LOWEST="--prefer-lowest"
  - PREFER_LOWEST=""

matrix:
  allow_failures:
  # fails due a segmentation fault
    - php: nightly
  # the tests require > 4.8GB ram on hhvm, this exeeds the memory limit on the travis-ci boxes so we allow to fail these builds
    - php: hhvm

before_script:
  - if [ "`phpenv version-name`" != "hhvm" ]; then echo 'opcache.enable=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - if [ "`phpenv version-name`" != "hhvm" ]; then echo 'opcache.enable_cli=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - if [ "`phpenv version-name`" == "hhvm" ]; then echo 'opcache.enable=1' >> /etc/hhvm/php.ini; fi
  - if [ "`phpenv version-name`" == "hhvm" ]; then echo 'opcache.enable_cli=1' >> /etc/hhvm/php.ini; fi
  - travis_retry composer self-update
  - travis_retry composer update -o --prefer-source --prefer-stable $PREFER_LOWEST

script:
# xdebug is not installed on hhvm and php7, so we are skipping the creation of code coverage data there
  - if [ "`phpenv version-name`" == "5.6" ]; then vendor/bin/phpunit -c phpunit.library.xml --colors --verbose --exclude-group useragenttest --coverage-text --coverage-clover=coverage.clover; fi
  - if [ "`phpenv version-name`" != "5.6" ]; then vendor/bin/phpunit -c phpunit.library.xml --colors --verbose --exclude-group useragenttest; fi
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --colors
#  - vendor/bin/phpcs --standard=psr2 -np src tests
#  - vendor/bin/php-cs-fixer fix --dry-run -vv

after_script:
# xdebug is not installed on hhvm and php7, so we have no code coverage data to send
  - if [ "`phpenv version-name`" == "5.6" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ "`phpenv version-name`" == "5.6" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi

