language: php
sudo: false

php:
  - 5.6
  - 7.0
  - nightly
  - hhvm

os:
  - linux

env:
  - PREFER_LOWEST="--prefer-lowest"
  - PREFER_LOWEST=""

matrix:
  allow_failures:
  # fails due a segmentation fault
    - php: nightly
  # the tests require > 4.8GB ram on hhvm, this exeeds the memory limit on the travis-ci boxes so we allow to fail these builds
    - php: hhvm

before_script:
  - if [ "`phpenv version-name`" != "hhvm" ]; then echo 'opcache.enable=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - if [ "`phpenv version-name`" != "hhvm" ]; then echo 'opcache.enable_cli=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - if [ "`phpenv version-name`" == "hhvm" ]; then echo 'opcache.enable=1' >> /etc/hhvm/php.ini; fi
  - if [ "`phpenv version-name`" == "hhvm" ]; then echo 'opcache.enable_cli=1' >> /etc/hhvm/php.ini; fi
  - travis_retry composer self-update
  - travis_retry composer update --optimize-autoloader --prefer-dist --prefer-stable --no-progress --no-interaction $PREFER_LOWEST

script:
# xdebug is not installed on hhvm and php7, so we are skipping the creation of code coverage data there
  - if [ "`phpenv version-name`" == "5.6" ]; then vendor/bin/phpunit -c phpunit.library.xml --exclude-group useragenttest --colors=auto --verbose --coverage-text --coverage-clover=coverage.clover; fi
  - if [ "`phpenv version-name`" != "5.6" ]; then vendor/bin/phpunit -c phpunit.library.xml --exclude-group useragenttest --colors=auto --verbose; fi
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00000 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00001 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00002 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00003 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00004 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00005 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00006 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00007 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00008 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00009 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00010 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00011 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00012 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00013 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00014 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00015 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00016 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00017 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00018 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00019 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00020 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00021 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00022 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00023 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00024 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00025 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00026 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00027 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00028 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00029 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00030 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00031 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00032 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00033 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00034 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00035 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00036 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00037 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00038 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00039 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00040 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00041 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00042 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00043 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00044 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00045 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00046 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00047 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00048 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00049 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00050 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00051 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00052 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00053 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00054 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00055 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00056 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00057 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00058 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00059 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00060 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00061 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00062 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00063 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00064 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00065 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00066 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00067 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00068 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00069 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00070 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00071 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00072 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00073 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00074 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00075 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00076 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00077 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00078 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00079 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00080 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00081 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00082 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00083 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00084 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00085 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00086 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00087 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00088 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00089 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00090 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00091 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00092 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00093 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00094 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00095 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00096 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00097 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00098 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00099 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00100 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00101 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00102 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00103 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00104 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00105 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00106 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00107 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00108 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00109 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00110 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00111 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00112 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00113 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00114 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00115 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00116 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00117 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00118 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00119 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00120 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00121 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00122 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00123 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00124 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00125 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00126 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00127 --colors=auto --verbose
  - vendor/bin/phpunit -c phpunit.compare.xml --no-coverage --group 00128 --colors=auto --verbose
#  - vendor/bin/phpcs --standard=psr2 -np src tests
#  - vendor/bin/php-cs-fixer fix --dry-run -vv

after_script:
# xdebug is not installed on hhvm and php7, so we have no code coverage data to send
  - if [ "`phpenv version-name`" == "5.6" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ "`phpenv version-name`" == "5.6" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi

